[build]
    publish = "dist"

    [[redirects]]
    from = "/ru"
    to = "/404.html"
    status = 404

    [[redirects]]
    from = "/en"
    to = "/404.html"
    status = 404

    [[redirects]]
    from = "/pl"
    to = "/404.html"
    status = 404

    [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200